version: '3'
services:
  mongo:
    image: mongo:4.2
    volumes:
      - mongo:/data/db
    ports:
      - ${DOCKER_MONGO_PORT}:27017

  comment-svc-dev:
    build: .
    ports: 
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - /var/log/dev/comment-svc:/usr/src/app/logs
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017
      DATABASE_NAME: ${DATABASE_NAME}

volumes:
  mongo: